### ISSUE TITLE
proc-macro2 v0.4.13 release breaks

### ISSUE THREAD

**Issue by alastairparagas** [alexcrichton/proc-macro2#118]
proc-macro2 is used as a dependency on `wasm-bindgen-backend`, `wasm-bindgen-macro-support` and `serde-derive`. Upon pulling and building the `0.4.13` version (released at around 10PM PST, August 16), it breaks.

```yaml
[dependencies]
wasm-bindgen = "0.2"
serde_json = "1.0"
regex = "1"
```

<img width="686" alt="screen shot 2018-08-17 at 3 29 02 am" src="https://user-images.githubusercontent.com/5952869/44261995-3e93ab00-a1ce-11e8-9d9d-424ca5553a12.png">

**Comment by dtolnay** [comment]
I am closing this issue because it looks like you are using an old version of nightly. The "nightly" feature of proc-macro2 which wasm-bindgen uses always only supports the most recent version of nightly i.e. "nightly" means that you upgrade the compiler "every night".

**Comment by jonathanstrong** [comment]
I came across this during probably my worst dependency conflict ever as an avid rust user.

I'm currently stuck using nightly-2018-08-06 because the compilers after that break a plugin that I use extensively and can't figure out how to fix yet. I am not listing proc-macro2 as a dep, but some of my deps do (as 0.4, which triggers the 0.4.14 update that's broken on nightly-2018-08-06).

I can't for the life of me figure out how to specify the dependency for a dependency without just making the 1st tier dependency a local path and manually changing its Cargo.toml. Any ideas? I realize this is perhaps not the best place to ask for help on this but it happened to be the exact error I encountered, and thought someone else might end up here in a similar spot.

**Comment by alexcrichton** [comment]
@jonathanstrong for this dependency itself it should be ok to upgrade `proc-macro2` to work with newer nightlies, but is there a different reason you can't upgrade nightlies other than `proc-macro2`?

**Comment by jonathanstrong** [comment]
@alexcrichton yes, I use a (non-open source) compiler plugin (`plugin_registar`) extensively in a large code base that breaks on nightly compilers more recent than around 2018-08-06. Obviously the `syntax` crate and other things are unstable so this can happen from time to time, but I haven't been able to figure out the problem yet. For some reason something that was previously eagerly evaluated at compile time now seems to be merely expanded. Anyway, this means I'm temporarily stuck on a specific nightly. I have serde dependencies all over the place, which in turn depend on proc-macro2. What I could not figure out how to do is specify the proc-macro2 version for my serde dependency. What I eventually did is clone serde, change its cargo manifest files, and point my crates to the local serde. It works but is not a sustainable fix.

**Comment by alexcrichton** [comment]
@jonathanstrong ah ok, this sounds like more of a dependency management issue than a `proc-macro2` issue, but you can use `cargo update -p proc-macro2 --precise x.y.z` to update your lock file to a specific version of `proc-macro2`

**Comment by jonathanstrong** [comment]
This is exactly what I was trying to do, thanks!
