### ISSUE TITLE
Add "impl PartialEq<&str> for Ident"

### ISSUE THREAD

**Issue by CreepySkeleton** [alexcrichton/proc-macro2#186]
Currently there's only one way to examine contents of an `Ident` - `&*ident.to_string() == "foo"`. I'd say this is kind of cumbersome and the more direct approach would be useful - `ident == "foo"`. 

By the way, I had encountered some people from the core team claim it's not safe to expose an a `str` reference from Ident - I don't know why and I would really love to be given an explanation. But keeping this in mind, still, proposed `impl` doesn't expose anything so it's should be safe anyway.

**Comment by CreepySkeleton** [comment]
Probably we could use `impl PartialEq<&str> for LitStr` too

**Comment by dtolnay** [comment]
This impl already exists. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ae1c744ddf36a9003556041a730a4dbe)

**Comment by CreepySkeleton** [comment]
Oooh... now I'm *really* curious why my code wasn't working. So what about `AsStr for Ident`? People just keep saying "no way, use to_string()` but nobody can explain why

**Comment by dtolnay** [comment]
Idents are stored in a thread local interner -- https://github.com/rust-lang/rust/issues/38356. That's why they are not Send. Exposing a conversion from &'a Ident to &'a str would be unsound because you could do `Box::leak(Box::new(ident))` to get a &'static Ident, convert to &'static str, hand it across to a different thread, have the original thread die and clear the interner, and then the &str continuing to exist would be undefined behavior.

**Comment by CreepySkeleton** [comment]
@dtolnay Thank's for clarification, I believe this issue should be closed
