### ISSUE TITLE
Raw identifiers are not accepted as Idents

### ISSUE THREAD

**Issue by hetoug** [alexcrichton/proc-macro2#245]
Raw identifiers in the form `r#ident` are not recognised as idents by the func `Ident::validate_ident`.

It seems that only the first part  of the definition in https://doc.rust-lang.org/reference/identifiers.html has been implemented.

**Comment by mystor** [comment]
This is intentional and mimics the behaviour of `proc_macro::Ident::new`, which will also fail with the message ["`r#ident` is not a valid identifier"](https://github.com/rust-lang/rust/blob/01ffbcbeed39b71c9939c7e67e39e59a5a09b254/src/librustc_expand/proc_macro_server.rs#L326).

The easiest way to get around this issue is to use the `format_ident!` macro from `quote` (https://docs.rs/quote/1.0.7/quote/macro.format_ident.html), which has special logic to support raw identifier parsing.

**Comment by dtolnay** [comment]
Yeah this matches the behavior of libproc_macro. For now you'd need to use format_ident or TokenStream::from_str to instantiate a raw Ident.
