### ISSUE TITLE
v1.0.19 -> v1.0.20: output of to_string change

### ISSUE THREAD

**Issue by Dushistov** [alexcrichton/proc-macro2#248]
```
use quote::quote;

fn main() {
    let ty = quote! { () };
    println!("{}", ty.to_string());
}
```

wiht <= 1.0.19 output will be: `(space)`,
with 1.0.20 output is `()` without spaces.
This also true for many other types, like `[T]` vs `[ T ]`.

**Comment by botika** [comment]
It is part of the version changes. For there to be a match between `proc_macro` and `proc_macro2`
https://github.com/alexcrichton/proc-macro2/pull/246

**Comment by dtolnay** [comment]
This is from #247 to resolve a behavior difference between proc-macro2 and libproc_macro.

I'll close because in general we don't commit to the to_string representation being permanently fixed. In order to operate with to_string'ed tokens you'd generally need to use from_str to turn them back into structured tokens first.
