### ISSUE TITLE
Convert Span to proc_macro::Span

### ISSUE THREAD

**Issue by antoyo** [alexcrichton/proc-macro2#35]
Hi.
It would be useful to be able to convert a `proc_macro2::Span` to a `proc_macro::Span`.
For instance, this will allow to create `Diagnostic`s with `Span`.
Thank you to add a `From` implementation for `unstable` only or something along these lines.

**Comment by alexcrichton** [comment]
Ah yeah currently this isn't done b/c this is functionality which can only be implemented with the `unstable` feature enabled, but seems reasonable to implement in that case to me!

**Comment by antoyo** [comment]
Either that or a function that returns `Span::call_site()` when the `unstable` feature is not enabled.
That will be very useful.
Thank you.

**Comment by mystor** [comment]
I have some WIP patches to add meaningful spans to the stable version of proc-macro2. It should allow us to expose those APIs from the span wrapper directly.

**Comment by alexcrichton** [comment]
Oh nice! Sounds good to me @mystor

**Comment by SergioBenitez** [comment]
I've actually made these changes in my form: https://github.com/SergioBenitez/proc-macro2. If these seem reasonable, @alexcrichton, I'd be happy to submit a PR.

**Comment by alexcrichton** [comment]
There's some work for this at https://github.com/alexcrichton/proc-macro2/pull/36, with the [conclusion at the end](https://github.com/alexcrichton/proc-macro2/pull/36#issuecomment-353171413) that what we should change is putting it behind an experimental feature.

**Comment by SergioBenitez** [comment]
The approach I've taken is a much simpler one: simply expose a method to retrieve a `proc_macro::Span`. This functionality is placed behind the "unstable" feature flag.

The reasoning here is that this approach relieves users of `proc-macro2` from depending on the library being updated for each piece of new functionality introduced in the nightly `proc-macro`.

I don't have any issue with also exposing the shims in #36 from `proc-macro2` so that libraries can be developed against this and then benefit from the real `proc-macro` when its released by deleting a couple of characters, however!

**Comment by alexcrichton** [comment]
Added in https://github.com/alexcrichton/proc-macro2/pull/41
